apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vortexuipro.fullname" . }}-panel-data
  labels:
    {{- include "vortexuipro.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
spec:
  accessModes:
    - {{ .Values.panel.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.panel.persistence.data.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vortexuipro.fullname" . }}-panel-backups
  labels:
    {{- include "vortexuipro.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
spec:
  accessModes:
    - {{ .Values.panel.persistence.backups.accessMode }}
  resources:
    requests:
      storage: {{ .Values.panel.persistence.backups.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
