apiVersion: v1
kind: Service
metadata:
  name: {{ include "vortexuipro.fullname" . }}-panel
  labels:
    {{- include "vortexuipro.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
spec:
  type: {{ .Values.panel.serviceType | default "ClusterIP" }}
  selector:
    {{- include "vortexuipro.panelSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.panel.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.panel.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: cluster
      port: {{ .Values.panel.clusterPort }}
      targetPort: cluster
      protocol: TCP
