apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vortexuipro.fullname" . }}-secrets
  labels:
    {{- include "vortexuipro.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.panel.secrets.jwtSecret }}
  jwt-secret: {{ .Values.panel.secrets.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.panel.secrets.databasePassword }}
  database-password: {{ .Values.panel.secrets.databasePassword | b64enc | quote }}
  {{- else }}
  database-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
